### ISSUE TITLE
How to increase the resolution up from 150x150?

### ISSUE THREAD

**Issue by priyangsubanerjee** [icancodebeauty/instagramdp#1]

**Comment by priyangsubanerjee** [comment]
This url has s150x150 ---> I tried replacing it with s320x320 ----> But got a url signature mismatch!

**Comment by a69y** [comment]
I Also Tried To Replace But Same `url signature mismatch` Error Shows!, If You Have Solution Please Make A PR!!

**Comment by a69y** [comment]
@priyangsubanerjee Try My New Library For Getting Full Size Images! => https://www.npmjs.com/package/instagrams

**Comment by priyangsubanerjee** [comment]
Thanks Yadavdotcodes/Instagramdp....I'll surely try out your new library.
